### ISSUE TITLE
Addon.exe throws error in Powershell

### ISSUE THREAD

**Issue by kavi99506** [azureautomation/azure-automation-ise-addon#158]
When i use Addon in PowerShell and login, I get error and not able to get automation account data.
Below is the error which i get.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at Microsoft.PowerShell.Host.ISE.PowerShellTab.PowerShellInvoker.Invoke[TOutput]()
   at Microsoft.PowerShell.Host.ISE.PowerShellTab.RefreshPromptPropertySynchronous()
   at Microsoft.PowerShell.Host.ISE.PowerShellTab.<>c__DisplayClass260_0.<InvokeSynchronous>b__0(Object <p0>)
   at Microsoft.Windows.PowerShell.Gui.Internal.WPFHelper.SendToUIThreadAndBlock(DispatcherOperationCallback dispatcherMethod)
   at Microsoft.PowerShell.Host.ISE.PowerShellTab.InvokeSynchronous(PSCommand psCommand, Int32 millisecondsTimeout)
   at Microsoft.PowerShell.Host.ISE.PowerShellTab.InvokeSynchronous(String script, Boolean useNewScope, Int32 millisecondsTimeout)
   at AutomationISE.AutomationISEControl.<accountsComboBox_SelectionChanged>d__62.MoveNext() in C:\addon\AutomationISE\AutomationISEControl.xaml.cs:line 890

**Comment by eamonoreilly** [comment]
Thanks for opening up this issue. Does this reproduce consistently?  Based on the call stack, It looks like it is try is trying to run the command in the PS window to shorten the path. Are you running anything else in the PS window when you are logging in?

**Comment by kavi99506** [comment]
I get this error when i try to login everytime from Powershell Addon. I am not running anything in PS window.

**Comment by kavi99506** [comment]
Any update on this?
